import Head from "next/head";
import Header from "@d20/Components/Header";
import { GetServerSideProps } from "next";

import { Session, getServerSession } from "next-auth";
import { authOptions } from "@d20/pages/api/auth/[...nextauth]";
interface Props {
  session: Session;
}

export default function Home({ session }: Props) {
  return (
    <div className="2">
      <Head>
        <title>Reddit 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
}

// export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
//   const session = await getServerSession(req, res, authOptions);

//   console.log("session", session);

//   return {
//     props: {
//       session,
//     },
//   };
// };
